<?php

namespace AppBundle\Repository;

/**
 * BlogRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BlogRepository extends \Doctrine\ORM\EntityRepository
{
     public function findAllForList()
    {
        $qb = $this->createQueryBuilder('c');

        $qb
            ->select('c')
            ->addOrderBy('c.publishedAt', 'DESC')
        ;

        return $qb->getQuery()->getResult();
    }

    public function findAllProcessedForList()
    {
        $qb = $this->createQueryBuilder('c');
        $qb
             ->select('c')
             ->addOrderBy('c.publishedAt', 'DESC')
         ;
    
         return $qb->getQuery()->getResult();
    }

}
