<?php

namespace AppBundle\Repository;

/**
 * ContactRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContactRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAllForList()
    {
        $qb = $this->createQueryBuilder('c');

        $qb
            ->select('c')
            ->addOrderBy('c.sentAt', 'DESC')
        ;

        return $qb->getQuery()->getResult();
    }

    // public function findAllProcessedForList()
    // {
    //     $qb = $this->createQueryBuilder('c');
    //
    //     $qb
    //         ->select('c')
    //         ->addWhere('c.processed IS TRUE')
    //         ->addOrderBy('c.sentAt', 'DESC')
    //     ;
    //
    //     return $qb->getQuery()->getResult();
    // }
}
